version: "3"
services:
  manager1:
    image: docker:dind
    privileged: true
    hostname: manager1
    ports:
      - "19000:9000"
      - "19001:9001"
  manager2:
    image: docker:dind
    privileged: true
    hostname: manager2
  worker1:
    image: docker:dind
    privileged: true
    hostname: worker1
  worker2:
    image: docker:dind
    privileged: true
    hostname: worker2
  portainer:
    image: portainer
    ports:
      - 19000:9000
    volumes:
      - "$PWD/endpoints.json:/endpoints.json:ro"
